version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl
    restart: always
    depends_on:
      - user-service
      - account-service
      - transaction-service
      - notification-service

  mongodb:
    image: mongo:latest
    container_name: mongodb-prod
    volumes:
      - mongodb_prod_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  user-service:
    image: ${REGISTRY_URL}/user-service:${TAG}
    env_file:
      - ./user-service/.env.prod
    restart: always
    depends_on:
      - mongodb
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  mail-service:
    image: ${REGISTRY_URL}/mail-service:${TAG}
    env_file:
      - ./mail-service/.env.prod
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  notification-service:
    image: ${REGISTRY_URL}/notification-service:${TAG}
    env_file:
      - ./notification-service/.env.prod
    depends_on:
      - user-service
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  account-service:
    image: ${REGISTRY_URL}/account-service:${TAG}
    env_file:
      - ./account-service/.env.prod
    depends_on:
      - user-service
      - mongodb
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  transaction-service:
    image: ${REGISTRY_URL}/transaction-service:${TAG}
    env_file:
      - ./transaction-service/.env.prod
    depends_on:
      - user-service
      - account-service
      - mongodb
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  mongodb_prod_data: 