apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
data:
  EXCEED_TRYS: "EXCEED"
  DB_Cloud_URl: "mongodb+srv://tyousef262:pFRnRyJt4BhXXsRA@cluster0.cwz5mhe.mongodb.net/instapay"
  TOKEN_LOGIN: "THIS TOKEN FOR LOGIN"
